Fix releasenote building
Releasennotes build fails with:

WARNING: html_static_path entry
u'/home/aj/vcs/OpenStack/openstack-dev/hacking/releasenotes/source/_static'
does not exist
ERROR: InvocationError:
'/home/aj/vcs/OpenStack/openstack-dev/hacking/.tox/releasenotes/bin/sphinx-build
-a -E -W -d releasenotes/build/doctrees -b html releasenotes/source
releasenotes/build/html'

Add - like in other projects - the directory using a placeholder file to
make git happy.

Change-Id: Ic012f5d02dbe8ecea30b7c6a10a94199dc5e809f